### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by uncttao** [ferrandi/PandA-bambu#16]
Is Bambu able to synthesize, in principle, any arbitrary C/C++ program _without_ any restrictions (e.g. forbidden use of certain language features, limited forms/bound of recursion)? Is it possible to look at a list of major restrictions if they exist? Thanks.

**Comment by ferrandi** [comment]
In principle, non-tail recursive functions is the only thing not supported.
For other language features, it much depends on the front-end compiler used. We rely on the Gimple IR from GCC and on the LLVM bitcode from Clang. Since those IRs are mostly language-independent, we are not suffering much on the C/C++ language feature restriction problems. Recursion is requiring a stack and such stack is not currently foreseen by the bambu steps. Anyway, there are things that could be problematic starting from GCC and not from CLANG or vice-versa. For example, variable-length arrays are currently supported by GCC, not by CLANG. C++ is better supported by CLANG front-end than GCC front-end. So, in case you are requiring some features you fill missing and not currently well supported, just open an issue.
Fabrizio

PS Note that some language features may not be translated efficiently. So variable-length arrays imply malloc and free which are introducing some computation overhead that are obviously not required by static arrays.
